ersion: "2"
services:
  practice_docker: 
    image: devmandy/node-rest-api
    ports: 
      - 80:3000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/architect
      - PORT=3000   
  db:
    image: postgres
    environment:
      - POSTGRES_USER=architect
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=api-db3